import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:3000';
const browser=await chromium.launch({channel:'chrome',headless:true});
await fs.mkdir('docs/qa',{recursive:true});
const report={checks:[],accessibility:[],errors:[]};
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
async function check(name,fn){try{await fn();report.checks.push({name,pass:true});console.log('PASS',name);}catch(e){report.checks.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message);}}
await check('Página inicial renderizada',async()=>{await page.goto(base);await page.getByRole('heading',{level:1}).waitFor();assert.match(await page.title(),/HS Eletrônicos/);await page.locator('.hero-board').evaluate(img=>img.decode());await page.screenshot({path:'docs/qa/desktop-home.png',fullPage:true});});
await check('Manifest e ícones',async()=>{const manifest=await (await page.request.get(base+'/manifest.webmanifest')).json();assert.equal(manifest.display,'standalone');assert.equal(manifest.lang,'pt-BR');for(const icon of manifest.icons){assert.equal((await page.request.get(base+icon.src)).status(),200);assert.ok(icon.sizes);}});
for(const route of ['/','/servicos/','/contato/','/instalar/']){
 await check('Acessibilidade '+route,async()=>{await page.goto(base+route);const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();report.accessibility.push({route,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});assert.equal(axe.violations.length,0,axe.violations.map(v=>v.id+': '+v.nodes.map(n=>n.target.join(' ')).join(',')).join('\n'));});
}
await check('Mensagem de WhatsApp real com codificação segura',async()=>{await page.goto(base+'/contato/?servico=Celular');await page.getByLabel('Marca e modelo').fill('Samsung A54 & teste');await page.getByLabel('O que você percebeu?').fill('Não carrega e começou hoje.');const url=new URL(await page.getByRole('link',{name:'Continuar no WhatsApp'}).getAttribute('href'));assert.equal(url.hostname,'wa.me');assert.equal(url.pathname,'/5531991137969');assert.match(url.searchParams.get('text'),/Samsung A54 & teste/);assert.match(url.searchParams.get('text'),/Equipamento: Celular/);assert.equal(await page.evaluate(()=>localStorage.length),0);await page.screenshot({path:'docs/qa/desktop-contact.png',fullPage:true});});
await check('FAQ expande e recolhe',async()=>{await page.goto(base+'/#duvidas');const detail=page.locator('details').first();await detail.locator('summary').click();assert.equal(await detail.evaluate(el=>el.open),true);await detail.locator('summary').click();assert.equal(await detail.evaluate(el=>el.open),false);});
await check('Todos os links internos existentes',async()=>{await page.goto(base);const links=await page.locator('a[href^="/"]').evaluateAll(items=>[...new Set(items.map(i=>i.getAttribute('href').split('#')[0]||'/'))]);for(const link of links)assert.equal((await page.request.get(base+link)).status(),200,link);for(const route of ['/servicos/iphone/','/servicos/celulares/','/servicos/eletronicos/','/sobre/','/links/','/offline/','/privacidade/'])assert.equal((await page.request.get(base+route)).status(),200,route);assert.equal((await page.request.get(base+'/pagina-inexistente/')).status(),404);});
const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>report.errors.push(e.message));
await check('Mobile 390px e menu acessível',async()=>{await mp.goto(base);await mp.getByRole('button',{name:'Abrir menu',exact:true}).click();assert.equal(await mp.getByRole('button',{name:'Fechar menu',exact:true}).getAttribute('aria-expanded'),'true');await mp.keyboard.press('Escape');assert.equal(await mp.getByRole('button',{name:'Abrir menu',exact:true}).getAttribute('aria-expanded'),'false');await mp.screenshot({path:'docs/qa/mobile-home.png',fullPage:true});});
await check('Sem overflow em 320, 390, 768 e 1440 px',async()=>{for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['/','/contato/','/servicos/iphone/','/instalar/']){await page.goto(base+route);const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));assert.ok(sizes.scroll<=sizes.client+1,`${width}px ${route} ${JSON.stringify(sizes)}`);}}});
await check('Service worker ativo',async()=>{await mp.goto(base);await mp.evaluate(()=>navigator.serviceWorker.ready);await mp.waitForFunction(()=>Boolean(navigator.serviceWorker.controller),{timeout:30000});const keys=await mp.evaluate(()=>caches.keys());assert.ok(keys.some(k=>k.startsWith('hs-eletronicos-')));});
await check('Rotas não visitadas disponíveis offline',async()=>{await mobile.setOffline(true);for(const route of ['/sobre/','/servicos/iphone/','/contato/']){await mp.goto(base+route);await mp.getByRole('heading',{level:1}).waitFor();assert.ok((await mp.locator('h1').innerText()).length>10);assert.equal(await mp.getByRole('status').filter({hasText:'Você está offline'}).count(),1);}await mp.getByRole('button',{name:'Aguardando conexão'}).waitFor();await mp.screenshot({path:'docs/qa/mobile-offline.png',fullPage:true});await mobile.setOffline(false);await mp.getByRole('link',{name:'Continuar no WhatsApp'}).waitFor();});
await check('Instruções de instalação disponíveis',async()=>{await mp.goto(base+'/instalar/');assert.ok(await mp.locator('.install-control').innerText());await mp.screenshot({path:'docs/qa/mobile-install.png',fullPage:true});});
await check('Nenhum erro de JavaScript',async()=>assert.deepEqual(report.errors,[]));
await fs.writeFile('docs/qa/browser-report.json',JSON.stringify(report,null,2));
await browser.close();
if(report.checks.some(c=>!c.pass))process.exitCode=1;
