"use client";
import { useEffect, useState } from 'react';
import { MessageCircle, Copy, ShieldCheck } from 'lucide-react';
import business from '@/lib/business.json';
import { composeMessage, whatsappUrl } from '@/lib/contact.mjs';
export function ContactForm(){
 const [category,setCategory]=useState('iPhone');const [model,setModel]=useState('');const [symptom,setSymptom]=useState('');const [status,setStatus]=useState('');const [online,setOnline]=useState(true);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);const value=new URLSearchParams(window.location.search).get('servico');if(value && ['iPhone','Celular','Outro eletrônico'].includes(value))setCategory(value);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 const message=composeMessage({category,model,symptom});const url=whatsappUrl(business.whatsapp,message);
 async function copy(){try{await navigator.clipboard.writeText(message);setStatus('Mensagem copiada. Você pode colar no WhatsApp.');}catch{setStatus('Não foi possível copiar automaticamente. Abra a prévia e copie o texto.');}}
 return <div className="contact-form"><h2>Conte o que aconteceu.</h2><p className="muted">Prepare sua mensagem. Você revisa e confirma o envio no WhatsApp.</p><fieldset><legend>Qual é o seu equipamento?</legend><div className="category-options">{['iPhone','Celular','Outro eletrônico'].map(item=><label key={item}><input type="radio" name="category" value={item} checked={category===item} onChange={()=>setCategory(item)}/><span>{item}</span></label>)}</div></fieldset><div className="field"><label className="field-label" htmlFor="model">Marca e modelo <span>opcional</span></label><input id="model" type="text" autoComplete="off" maxLength={80} placeholder="Ex.: iPhone 13" value={model} onChange={e=>setModel(e.target.value)}/></div><div className="field"><label className="field-label" htmlFor="symptom">O que você percebeu? <span>opcional</span></label><textarea id="symptom" maxLength={500} placeholder="Conte o sintoma e quando ele começou." value={symptom} onChange={e=>setSymptom(e.target.value)} aria-describedby="privacy-note"/><p id="privacy-note" className="field-note">Não inclua senhas, códigos de verificação ou informações pessoais do aparelho.</p></div><details className="message-preview"><summary>Revisar minha mensagem</summary><pre>{message}</pre></details>{!online&&<p className="notice">Você está offline. Pode preparar e copiar a mensagem, mas precisa de internet para abrir o WhatsApp.</p>}<div className="form-actions">{url&&online?<a className="button" href={url} target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/>Continuar no WhatsApp</a>:<button className="button" disabled><MessageCircle size={19}/>{online?'Canal em atualização':'Aguardando conexão'}</button>}<button className="button outline" type="button" onClick={copy}><Copy size={17}/>Copiar mensagem</button></div><p role="status" className="form-status">{status}</p><p className="field-note"><ShieldCheck size={14} style={{verticalAlign:'middle'}}/> Nada é enviado à HS por esta página. O texto fica apenas nesta sessão até você abrir o WhatsApp.</p></div>;
}
