"use client";
import { useEffect, useState } from 'react';
import { Download, WifiOff, RefreshCw, CheckCircle2, Share2 } from 'lucide-react';
type InstallEvent = Event & { prompt:()=>Promise<void>; userChoice:Promise<{outcome:string}> };
let deferredInstall: InstallEvent | null = null;
export function PwaStatus(){const [offline,setOffline]=useState(false);const [worker,setWorker]=useState<ServiceWorker|null>(null);
 useEffect(()=>{const capture=(event:Event)=>{event.preventDefault();deferredInstall=event as InstallEvent;window.dispatchEvent(new Event('hs-install-ready'));};const clear=()=>{deferredInstall=null;};window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',clear);setOffline(!navigator.onLine);const on=()=>setOffline(!navigator.onLine);window.addEventListener('online',on);window.addEventListener('offline',on);
 if('serviceWorker' in navigator && process.env.NODE_ENV==='production') {navigator.serviceWorker.register('/sw.js',{scope:'/'}).then(reg=>{const check=()=>{if(reg.waiting && navigator.serviceWorker.controller)setWorker(reg.waiting);};check();reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',check);});reg.update().catch(()=>{});}).catch(()=>{});}
 return()=>{window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',clear);window.removeEventListener('online',on);window.removeEventListener('offline',on);};},[]);
 const update=()=>{if(!worker)return; navigator.serviceWorker.addEventListener('controllerchange',()=>window.location.reload(),{once:true});worker.postMessage({type:'SKIP_WAITING'});};
 return <>{offline&&<div className="connection-banner" role="status"><WifiOff size={16}/>Você está offline. As informações salvas continuam disponíveis; o WhatsApp precisa de conexão.</div>}{worker&&<div className="update-banner" role="status"><RefreshCw size={16}/><span>Uma nova versão está disponível.</span><button onClick={update}>Atualizar agora</button><button onClick={()=>setWorker(null)} aria-label="Dispensar atualização">Depois</button></div>}</>;
}
export function InstallControl(){const [prompt,setPrompt]=useState<InstallEvent|null>(null);const [installed,setInstalled]=useState(false);const [ios,setIos]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{setPrompt(deferredInstall);const sync=()=>setPrompt(deferredInstall);window.addEventListener('hs-install-ready',sync);const media=window.matchMedia('(display-mode: standalone)');setInstalled(media.matches || Boolean((navigator as Navigator & {standalone?:boolean}).standalone));setIos(/iPad|iPhone|iPod/.test(navigator.userAgent)|| (navigator.platform==='MacIntel' && navigator.maxTouchPoints>1));const capture=(event:Event)=>{event.preventDefault();setPrompt(event as InstallEvent);};const done=()=>{setInstalled(true);setPrompt(null);};window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',done);const change=()=>setInstalled(media.matches);media.addEventListener('change',change);return()=>{window.removeEventListener('hs-install-ready',sync);window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',done);media.removeEventListener('change',change);};},[]);
 async function install(){if(!prompt)return;await prompt.prompt();const choice=await prompt.userChoice;setNotice(choice.outcome==='accepted'?'Siga a confirmação do navegador para concluir a instalação.':'Você pode continuar usando pelo navegador.');setPrompt(null);deferredInstall=null;}
 return <div className="install-control">{installed?<div className="success-note"><CheckCircle2/>Você já está usando o aplicativo instalado.</div>:prompt?<button className="button" onClick={install}><Download size={20}/>Instalar HS Eletrônicos</button>:<div className="install-instructions"><h2>{ios?'No iPhone ou iPad':'Instalar pelo navegador'}</h2>{ios?<ol><li>Abra este site no Safari.</li><li>Toque em Compartilhar <Share2 size={15}/>.</li><li>Selecione Adicionar à Tela de Início e confirme.</li></ol>:<ol><li>Abra este site no Chrome ou Edge atualizado.</li><li>No menu, procure Instalar aplicativo ou Adicionar à tela inicial.</li><li>Confirme para criar o atalho da HS.</li></ol>}<p className="muted">A opção depende do navegador. Você pode usar todos os serviços pelo site sem instalar.</p></div>}<p role="status">{notice}</p></div>;
}
