import Link from 'next/link';
import { Clock3, MessageCircle, Smartphone, Cpu, Check, MapPin, Headphones } from 'lucide-react';
import { faqs, services } from '@/lib/data';
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>;}
export function Breadcrumb({label}:{label:string}){return <nav className="breadcrumb" aria-label="Caminho da página"><Link href="/">Início</Link><span>/</span><span aria-current="page">{label}</span></nav>;}
export function ServiceCards(){return <div className="service-grid">{services.map((s,i)=><article className={`service-card service-card-${i}`} key={s.slug}><span className="card-index">0{i+1}</span><div className="service-icon">{s.icon==='phone'?<Smartphone size={30}/>:<Cpu size={30}/>}</div><h3>{s.title}</h3><p>{s.description}</p><Link className="text-link" href={`/servicos/${s.slug}/`}>Conhecer atendimento<span className="visually-hidden"> para {s.title}</span></Link></article>)}</div>;}
export function Process(){return <section className="section process-section" id="como-funciona"><div className="container"><div className="section-heading"><div><Eyebrow>UM PASSO DE CADA VEZ</Eyebrow><h2>Da primeira conversa<br/>ao próximo passo.</h2></div><p>Clareza para entender o que seu aparelho precisa, começando pelo contato.</p></div><div className="process-grid">{[{icon:MessageCircle,title:'Conte o que aconteceu',body:'Informe o modelo do aparelho e o sintoma percebido.'},{icon:MapPin,title:'Combine o atendimento',body:'Fale com Hugo sobre o local e como iniciar a avaliação.'},{icon:Check,title:'Entenda as possibilidades',body:'Confirme o serviço, as condições e o prazo antes de decidir.'}].map((s,i)=><article key={s.title}><span className="step-number">0{i+1}</span><s.icon size={25}/><h3>{s.title}</h3><p>{s.body}</p></article>)}</div></div></section>;}
export function Faq(){return <section className="section" id="duvidas"><div className="container faq-layout"><div><Eyebrow>SEM COMPLICAÇÃO</Eyebrow><h2>Antes de<br/>entrar em contato.</h2><p>Respostas para começar a conversa com mais tranquilidade.</p><Link className="text-link" href="/contato/">Minha dúvida é outra</Link></div><div className="faqs">{faqs.map(([q,a],i)=><details key={q}><summary><span className="faq-number">0{i+1}</span>{q}<span className="faq-plus" aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>;}
export function ContactBanner(){return <section className="container contact-banner"><div><span className="availability"><Clock3 size={15}/>ATENDIMENTO 24H</span><h2>Vamos cuidar do<br/>seu próximo passo?</h2><p>Converse com Hugo e combine o atendimento em BH e região.</p></div><Link className="button" href="/contato/"><MessageCircle size={20}/>Combinar atendimento</Link></section>;}
