import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Check, Clock3, MessageCircle } from 'lucide-react';
import { services } from '@/lib/data';
import { Breadcrumb, Eyebrow, Faq, ContactBanner } from '@/components/ui';
export const dynamicParams=false;
export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.slug===slug);return {title:s?`Assistência para ${s.title}`:'Serviço não encontrado',description:s?.description};}
export default async function Service({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();const category=s.slug==='iphone'?'iPhone':s.slug==='celulares'?'Celular':'Outro eletrônico';return <><div className="container"><Breadcrumb label={`Serviços / ${s.title}`}/><div className="page-intro"><Eyebrow>{s.label}</Eyebrow><h1>Assistência para<br/>{s.title.toLowerCase()==='iphone'?'iPhone':s.title.toLowerCase()}.</h1><p>{s.intro}</p></div><div className="page-content detail-grid"><div><h2>Para começar a conversa</h2><ul className="check-list">{s.topics.map(t=><li key={t}><Check size={19}/>{t}</li>)}</ul><p>Informe o que você percebeu no aparelho. Esses detalhes ajudam Hugo a orientar como iniciar o atendimento.</p><div>{s.examples.map(e=><span className="tag" key={e}>{e}</span>)}</div><p className="notice">{s.note}</p><Link className="text-link" href="/servicos/">Ver todos os serviços</Link></div><aside className="detail-aside"><Clock3 size={28} color="#167c54"/><h2 style={{marginTop:22}}>Conte com a HS<br/>a qualquer hora.</h2><p>Atendimento presencial e reparação 24h em BH e região. Entre em contato para combinar o local e a avaliação.</p><Link className="button" href={`/contato/?servico=${encodeURIComponent(category)}`}><MessageCircle size={18}/>Combinar atendimento</Link><p className="field-note" style={{marginBottom:0}}>O prazo e as condições do serviço são confirmados conforme o caso.</p></aside></div></div><Faq/><ContactBanner/></>;}
