import sys
sys.path.insert(0, r'C:\Users\Fabio\Desktop\HS Eletronicos\05_Fontes_e_QA\dependencias')
from pathlib import Path
import json, html
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.colors import HexColor
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
import pypdfium2 as pdfium
from PIL import Image, ImageOps, ImageDraw
R=Path(r'C:\Users\Fabio\Desktop\HS Eletronicos')
pdfmetrics.registerFont(TTFont('Arial',r'C:\Windows\Fonts\arial.ttf'))
pdfmetrics.registerFont(TTFont('ArialBold',r'C:\Windows\Fonts\arialbd.ttf'))
INK='#102A35'; GREEN='#B8EF48'; WHITE='#F5F7F2'; GRAY='#52666D'
P=[]
def page(k,t,lead,items): P.append(dict(k=k,t=t,lead=lead,items=items))
page('01 / ESSÊNCIA','Tecnologia de volta à vida.','HS Eletrônicos | Brandbook 1.0 • Proposta para validação • Outubro 2026', [('O negócio','Reparação de equipamentos eletrônicos, com prioridade em celulares e iPhones. Compra e venda de equipamentos novos e seminovos.'),('A direção','Uma marca técnica, próxima e organizada. A identidade conecta o cuidado com o aparelho à clareza no atendimento.'),('Como ler este manual','Estratégia e design propostos. Contatos, histórico, condições comerciais e diferenciais operacionais ainda dependem de confirmação.')])
page('02 / FUNDAMENTOS','Confiança se demonstra.','A marca deve tornar visível o cuidado que acontece na bancada.', [('Propósito proposto','Ajudar as pessoas a manter sua vida conectada por meio do cuidado com seus equipamentos.'),('Missão proposta','Reparar e comercializar eletrônicos com orientação compreensível e informação suficiente para uma escolha consciente.'),('Visão proposta','Ser lembrada em Belo Horizonte e região pela qualidade do atendimento e pela clareza em cada etapa. Horizonte a definir.'),('Valores em ação','Precisão: avaliar antes de concluir. Clareza: explicar escopo e condições. Respeito: cuidar do aparelho e dos dados. Responsabilidade: comunicar limites e imprevistos.')])
page('03 / POSICIONAMENTO','Especialização que aproxima.','Foco em reparação; comércio como extensão da relação de confiança.', [('Posicionamento proposto','Para quem, em Belo Horizonte e região, precisa reparar um celular ou escolher outro equipamento, a HS Eletrônicos oferece atendimento técnico com foco em iPhones e comunicação simples sobre o que está sendo contratado.'),('Promessa de marca','Cuidado técnico. Conversa clara.'),('Razões para acreditar a construir','Registrar diagnóstico, orçamento, autorização, serviço executado e testes de entrega. Estes processos são recomendações; não foram confirmados como práticas atuais.'),('Território','Especialista acessível: aparência organizada, linguagem humana e evidências do trabalho. Evitar luxo distante e promoções que escondem condições.')])
page('04 / PÚBLICOS','Três necessidades. Uma marca.','Hipóteses de público para validar com o histórico real de atendimento.', [('01 • Preciso do meu celular','Pessoa que depende do aparelho para trabalho e rotina. Quer entender problema, custo, prazo e próximos passos. Mensagem: “Conte o que aconteceu com seu aparelho.”'),('02 • Quero cuidar do meu iPhone','Pessoa que valoriza o dispositivo e busca atenção técnica. Quer informações sobre peças, processo e testes. Mensagem: “Entenda as opções para o seu iPhone.”'),('03 • Quero comprar ou vender','Pessoa que busca uma negociação compreensível. Precisa saber estado, capacidade, condições e disponibilidade. Mensagem: “Escolha com informação.”')])
page('05 / ARQUITETURA','HS Eletrônicos, sempre.','Uma marca única evita fragmentação entre assistência e comércio.', [('Nome','Usar “HS Eletrônicos” nos textos e “HS ELETRÔNICOS” na assinatura visual. “HS Eletronicos” fica reservado a nomes de pasta, URLs e campos sem acentos.'),('Descritores','Principal: Reparação de celulares. Complementar: Compra e venda de eletrônicos. Usar “Foco em iPhones” em textos de apoio, sem incorporar ao nome.'),('Organização de serviços','Reparação de celulares / Outros eletrônicos / Equipamentos novos e seminovos / Avaliação para compra. Publicar somente categorias efetivamente atendidas.'),('Assinatura verbal','“Tecnologia de volta à vida.” para campanhas institucionais. “Cuidado técnico. Conversa clara.” para apresentar a proposta de atendimento.')])
page('06 / VOZ','Explique como quem cuida.','Direta, tranquila e específica. A técnica deve ajudar a decisão.', [('Tom','Use frases curtas e verbos concretos. Explique termos técnicos na primeira menção. Fale com “você”. Em situações de defeito, comece acolhendo a dúvida.'),('Exemplo • orçamento','“Precisamos avaliar o aparelho para identificar a causa. Depois, apresentamos as opções e o orçamento.”'),('Exemplo • imprevisto','“Na avaliação, encontramos outro ponto que precisa de atenção. Vamos explicar o que muda antes de continuar.”'),('Evitar','“Melhor da cidade”, “100% garantido”, “conserto na hora”, “peça original” e “autorizada” sem comprovação. Não apresentar prazo ou diagnóstico definitivo por uma foto.')])
page('07 / IDENTIDADE','Um sinal de continuidade.','Símbolo geométrico HS: duas iniciais, uma linha de conexão.', [('Conceito','O H organiza a estrutura; o S cria um percurso contínuo. A linha central remete à conexão e ao fluxo de trabalho, sem depender da silhueta de um aparelho.'),('Construção','Símbolo em grade de 100 × 100 unidades. Traços de 10 unidades, terminações quadradas e segmentos ortogonais. A união visual das iniciais é intencional.'),('Personalidade visual','Azul profundo para estrutura. Lima para pontos de atenção. Fundo claro para explicar. Formas simples e espaço em branco reforçam organização.'),('Status','Desenho original desta proposta, ainda sujeito à aprovação e à verificação de disponibilidade do nome e do sinal antes da adoção comercial.')])
page('08 / ASSINATURAS','Reconhecimento em qualquer escala.','Os SVGs fornecidos são os arquivos mestres da proposta.', [('Horizontal • principal','Símbolo à esquerda, nome à direita. Usar no site, orçamento e peças horizontais. Versões positiva e negativa.'),('Símbolo • compacto','Usar em avatar e favicon depois que a marca estiver identificada no contexto. Não substituir o nome em primeiro contato comercial.'),('Monocromática','Aplicar em uma única tinta quando a produção exigir. As versões preta e branca preservam a estrutura.'),('Área de proteção','Manter no mínimo 20 unidades da grade do símbolo livres ao redor da assinatura. Não incluir texto, bordas ou fotos nessa área.')])
page('09 / REPRODUÇÃO','Legibilidade é a regra.','Limites iniciais de uso; conferir a prova no tamanho final.', [('Tamanhos mínimos','Assinatura horizontal: 200 px em tela ou 45 mm em impressão. Símbolo isolado: 24 px ou 7 mm. Entre 16 e 23 px, usar favicon simplificado e verificar a leitura.'),('Fundos','Positiva sobre fundo claro. Negativa sobre azul profundo. Sobre fotografia, criar uma área sólida que preserve o contraste.'),('Usos proibidos','Não esticar, girar, alterar a distância entre elementos, aplicar sombras, trocar cores arbitrariamente ou reconstruir o símbolo com uma fonte.'),('Coexistência','Marcas de fabricantes só quando necessárias para identificar produtos. A HS deve aparecer como a marca do negócio; não sugerir vínculo oficial não confirmado.')])
page('10 / CORES','Profundidade + energia.','Uma base calma com um acento reconhecível.', [('Petróleo • #102A35','RGB 16 / 42 / 53. Cor principal, títulos, fundos escuros e texto.'),('Lima • #B8EF48','RGB 184 / 239 / 72. Acento, pequenos destaques e chamadas com texto petróleo. Não usar para texto sobre branco.'),('Névoa • #F5F7F2','RGB 245 / 247 / 242. Fundo principal e texto sobre petróleo.'),('Ardósia • #52666D','RGB 82 / 102 / 109. Texto secundário sobre névoa. Proporção inicial: 60% névoa, 30% petróleo, 10% lima. Para impressão, converter com o perfil da gráfica e aprovar prova; HEX não garante equivalência física.')])
page('11 / TIPOGRAFIA','Informação antes do efeito.','Arial organiza a primeira versão com ampla disponibilidade.', [('Família','Arial Regular para corpo e Arial Bold para títulos. Fallback digital: Arial, Helvetica, sans-serif. Não distribuir os arquivos de fonte; usar a licença disponível em cada ambiente.'),('Hierarquia digital','Título 48/52 px em desktop e 34/38 px em mobile. Subtítulo 24/30 px. Corpo 16/24 px. Rótulo 12/16 px. Ajustar conforme conteúdo, preservando a ordem visual.'),('Composição','Alinhar à esquerda. Evitar parágrafos em caixa alta. Limitar textos longos a cerca de 65 caracteres por linha. Preferir peso e espaço a muitos tamanhos diferentes.'),('Texto e botões','Ação explícita: “Solicitar avaliação”, “Ver equipamentos”, “Falar com a HS”. Evitar botões vagos como “Clique aqui”.')])
page('12 / SISTEMA GRÁFICO','Precisão com espaço para respirar.','A identidade nasce do símbolo e de uma composição consistente.', [('Grade','Espaçamento em múltiplos de 8 px. Margens digitais de 24 px no celular e 64 px em áreas amplas. Cards com raio de 16 px e borda discreta.'),('Grafismos','Linhas ortogonais derivadas do HS podem enquadrar detalhes e conectar blocos. Usar como apoio, nunca atrás de texto pequeno.'),('Ícones','Contorno uniforme, cantos simples e desenho legível. Usar ícones de serviço, avaliação e contato sem substituir os rótulos.'),('Fotografia','Mostrar bancada real organizada, mãos em trabalho e equipamentos do estoque. Luz difusa, fundo limpo e cores naturais. Não usar imagens de banco como prova de serviço realizado.')])
page('13 / EXPERIÊNCIA','A marca também atende.','Fluxo recomendado para tornar a promessa verificável.', [('Receber','Perguntar modelo, sintoma e contexto. Registrar estado aparente e combinar o próximo contato. Explicar se a avaliação tem custo antes de iniciá-la.'),('Orientar','Apresentar diagnóstico, opções, itens do orçamento e previsão. Explicar condições antes da autorização.'),('Executar e informar','Registrar autorização e comunicar alterações de escopo. Evitar divulgar dados de clientes ou conteúdo de telas em fotos e vídeos.'),('Entregar','Apresentar o que foi feito, testes e cuidados. Informar por escrito as condições aplicáveis. Prazos e políticas precisam ser definidos pelo negócio.')])
page('14 / COMÉRCIO','Produto bem descrito vende confiança.','Novo e seminovo precisam de informação clara e individual.', [('Ficha de produto','Modelo, capacidade, cor, estado, marcas de uso, acessórios, preço, pagamento e disponibilidade. Em seminovos, incluir as verificações realizadas e observações relevantes.'),('Linguagem','“Seminovo” não substitui a descrição do estado. Usar fotos do equipamento anunciado e destacar limitações conhecidas.'),('Compra de aparelhos','“Envie modelo e informações sobre o estado para iniciar a avaliação.” Não prometer preço de compra antes da análise.'),('Modelo de anúncio','“[Modelo] • [capacidade]. Estado: [descrição]. Acompanha: [itens]. Valor: [preço e condições]. Consulte a disponibilidade.” Campos entre colchetes são dados a preencher, nunca publicação pronta.')])
page('15 / SITE','Primeiro, resolver a necessidade.','Direção para a próxima etapa: site com hospedagem prevista na Vercel.', [('Objetivo principal','Gerar contatos qualificados para reparação. Objetivo secundário: apresentar equipamentos disponíveis e o serviço de compra.'),('Estrutura','Início / Reparação / Equipamentos / Sobre a HS / Contato. Se o conteúdo inicial for pequeno, começar em uma página com essas seções.'),('Primeira dobra','Título: “Seu celular merece atenção técnica.” Apoio: “Reparação de celulares com foco em iPhones. Fale com a HS e entenda o próximo passo.” CTA: “Solicitar avaliação”.'),('Confiança e conversão','Mostrar processo real, fotos próprias e informações verificadas. Incluir cidade, horário e contato confirmados. Não criar avaliações, números de clientes ou certificações fictícias.')])
page('16 / INTERFACE','Uma experiência clara no celular.','Referências visuais de componentes, sem implementação do site nesta etapa.', [('Botão principal','Fundo lima + texto petróleo, altura inicial 48 px, rótulo curto. Foco visível e estados de interação distintos.'),('Card de serviço','Nome do serviço, descrição compreensível e ação. Não usar preço fixo quando depender de avaliação.'),('Card de equipamento','Foto real, modelo, condição, preço e disponibilidade. Evitar carrosséis que escondem dados essenciais.'),('Base técnica a definir','Layout responsivo, imagens otimizadas e contato funcional. Confirmar domínio, canais e atualização do estoque antes de escolher CMS e fluxo de publicação na Vercel.')])
page('17 / REDES SOCIAIS','Mostre o cuidado acontecendo.','Proposta editorial inicial para Instagram e TikTok.', [('45% • Processo e confiança','Bastidores, testes e explicações do atendimento. Evidência real com consentimento e sem exposição de dados.'),('30% • Educação','Perguntas frequentes, sinais que merecem avaliação e cuidados de uso. Evitar diagnóstico universal e instruções arriscadas para o público.'),('15% • Equipamentos','Novidades do estoque, detalhes de estado e comparações pertinentes. Atualizar disponibilidade.'),('10% • Marca e relacionamento','Apresentação do reparador, rotina, localização e dúvidas da comunidade. Percentuais são uma hipótese editorial, não dados de desempenho.')])
page('18 / FORMATOS','Uma linguagem, vários enquadramentos.','Templates internos propostos; conferir a interface de cada plataforma ao publicar.', [('Feed vertical','Matriz de 1080 × 1350 px. Uma ideia por peça, título curto e hierarquia forte. Margem interna mínima de 72 px.'),('Vídeo e stories','Matriz de 1080 × 1920 px. Reservar topo, rodapé e lateral direita para possíveis sobreposições da interface; revisar na prévia do aplicativo.'),('Legendas e movimento','Legendas de alto contraste, duas linhas por vez. Cortes motivados pela explicação. Grafismos discretos; evitar ruído visual e flashes.'),('Capa e CTA','Capa com assunto identificável: “Como funciona a avaliação?”. Encerrar com uma ação pertinente: “Conte o que aconteceu com seu aparelho”.')])
page('19 / ROTEIROS','Três histórias para começar.','Duração indicativa de 20 a 35 segundos; ajustar ao material real.', [('01 • Antes do reparo','Abertura: “O primeiro passo é entender o problema.” Mostrar recepção, análise e orçamento sem dados pessoais. Fecho: “Fale com a HS para saber como iniciar a avaliação.”'),('02 • Quem cuida do seu aparelho','Apresentar o profissional pelo nome confirmado. Mostrar bancada e explicar uma etapa real. Fecho: “Cuidado técnico. Conversa clara.” Não inventar formação ou tempo de mercado.'),('03 • Escolher um seminovo','Mostrar um item real e três informações: estado, capacidade e acessórios. Exibir preço e condições atualizados. Fecho: “Consulte a disponibilidade com a HS.”')])
page('20 / PLANO INICIAL','Quatro semanas de consistência.','Cadência proposta: dois conteúdos principais por semana, com stories de apoio.', [('Semana 1 • Apresentação','Vídeo: quem é a HS. Carrossel: como funciona a avaliação. Stories: bancada e respostas a dúvidas reais.'),('Semana 2 • Confiança','Vídeo: etapa de teste de um serviço real. Post: o que informar ao pedir uma avaliação. Stories: bastidores autorizados.'),('Semana 3 • Escolha','Vídeo: como ler uma ficha de seminovo. Post: equipamento disponível com ficha completa. Stories: atualização do estoque.'),('Semana 4 • Relacionamento','Vídeo: resposta a uma pergunta frequente. Carrossel: cuidados após o atendimento, validados pelo reparador. Medir contatos qualificados, dúvidas e conteúdos salvos para ajustar a pauta.')])
page('21 / APLICAÇÕES','Da tela à bancada.','Aplicações conceituais; produção física exige prova do fornecedor.', [('Avatar','Símbolo petróleo em campo lima, centralizado e com respiro. Testar dentro do recorte circular.'),('Cartão e assinatura','Nome da marca, descritor, contato e cidade confirmados. QR code apenas após definir e testar o destino.'),('Fachada e uniforme','Assinatura com leitura à distância; priorizar contraste. Uniforme em petróleo com marca clara, respeitando a área de proteção.'),('Orçamento e embalagem','Cabeçalho com marca e contato; corpo limpo para itens e condições. Adesivo institucional sem promessas comerciais não confirmadas.')])
page('22 / GOVERNANÇA','Uma base pronta para evoluir.','O sistema está proposto. A aprovação deve transformar hipóteses em decisões.', [('Validar com o cliente','Significado de HS; nome comercial; público; preferências visuais; serviços aceitos; diferenciais comprováveis; contatos e políticas de atendimento.'),('Antes de publicar','Conferir textos, imagens, dados comerciais e disponibilidade do nome. Confirmar eventuais vínculos com fabricantes antes de qualquer menção institucional.'),('Responsáveis e versões','Definir um responsável por aprovar marca e conteúdo. Guardar os mestres; registrar alterações de versão. V1.0 é proposta inicial, não aprovação do cliente.'),('Próximas entregas','Após validação: ajustes finais da identidade; implementação do site; produção de templates e conteúdos reais. Este pacote oferece a base e exemplos conceituais para essas etapas.')])
# SVG masters use outlines for name, avoiding font dependencies.
from reportlab.graphics.shapes import String
from fontTools.ttLib import TTFont as FTFont
from fontTools.pens.svgPathPen import SVGPathPen
font=FTFont(r'C:\Windows\Fonts\arialbd.ttf'); glyphs=font.getGlyphSet(); cmap=font.getBestCmap(); units=font['head'].unitsPerEm

def outlined(text,x,y,size):
 out=[]; scale=size/units
 for ch in text:
  name=cmap[ord(ch)]; pen=SVGPathPen(glyphs); glyphs[name].draw(pen)
  out.append(f'<path d="{pen.getCommands()}" transform="translate({x:.3f} {y}) scale({scale} {-scale})"/>'); x+=font['hmtx'][name][0]*scale
 return ''.join(out)
mark='M15 15V85 M45 15V85 M15 50H85 V85 H60 M85 15H60 V50'
for variant,fg,bg in [('principal',INK,None),('negativo',WHITE,INK),('preto','#000000',None),('branco','#FFFFFF',None)]:
 svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 560 140"><title>HS Eletrônicos</title>'+(f'<rect width="560" height="140" fill="{bg}"/>' if bg else '')+f'<g transform="translate(20 20)" fill="none" stroke="{fg}" stroke-width="10"><path d="{mark}"/></g><g fill="{fg}">'+outlined('HS ELETRÔNICOS',145,76,37)+outlined('CUIDADO TÉCNICO. CONVERSA CLARA.',146,104,12)+'</g></svg>'
 (R/'02_Identidade/logos'/f'hs-horizontal-{variant}.svg').write_text(svg,encoding='utf-8')
for name,fg,bg in [('simbolo',INK,None),('avatar',INK,GREEN),('favicon',INK,GREEN)]:
 (R/'02_Identidade/logos'/f'hs-{name}.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 140 140"><title>HS</title>'+(f'<rect width="140" height="140" rx="24" fill="{bg}"/>' if bg else '')+f'<path transform="translate(20 20)" d="{mark}" fill="none" stroke="{fg}" stroke-width="10"/></svg>',encoding='utf-8')

def markpdf(c,x,y,s,fg=INK):
 c.saveState(); c.translate(x,y); c.scale(s/100,s/100); c.setStrokeColor(HexColor(fg)); c.setLineWidth(10)
 p=c.beginPath();p.moveTo(15,15);p.lineTo(15,85);p.moveTo(45,15);p.lineTo(45,85);p.moveTo(15,50);p.lineTo(85,50);p.lineTo(85,15);p.lineTo(60,15);p.moveTo(85,85);p.lineTo(60,85);p.lineTo(60,50);c.drawPath(p);c.restoreState()
W,H=960,600
c=canvas.Canvas(str(R/'01_Brandbook/HS_Eletronicos_Brandbook_v1.pdf'),pagesize=(W,H));c.setTitle('HS Eletrônicos | Brandbook v1.0');c.setAuthor('HS Eletrônicos • Proposta de identidade')
def para(txt,x,y,w,size=13,color=INK,bold=False):
 p=Paragraph(html.escape(txt),ParagraphStyle('p',fontName='ArialBold' if bold else 'Arial',fontSize=size,leading=size*1.4,textColor=HexColor(color)))
 _,h=p.wrap(w,1000);p.drawOn(c,x,y-h);return h
for i,p in enumerate(P):
 c.setFillColor(HexColor(WHITE));c.rect(0,0,W,H,fill=1,stroke=0)
 c.setFillColor(HexColor(INK));c.rect(0,0,255,H,fill=1,stroke=0)
 markpdf(c,48,410,155,GREEN)
 para('HS\nELETRÔNICOS'.replace('\n',' '),36,395,188,20,WHITE,True)
 para(p['k'],36,335,180,12,GREEN,True)
 para('Cuidado técnico. Conversa clara.',36,288,175,21,WHITE)
 para('PROPOSTA 1.0\nOUTUBRO 2026'.replace('\n',' / '),36,75,190,9,WHITE)
 para(p['t'],295,547,615,29,INK,True)
 para(p['lead'],295,492,610,13,GRAY)
 y=435
 for title,body in p['items']:
  h=para(title,295,y,610,14,INK,True);y-=h+5
  h=para(body,295,y,610,12,GRAY);y-=h+20
 assert y>42,(i,y)
 c.setFillColor(HexColor(GREEN));c.rect(295,29,45,4,fill=1,stroke=0)
 para(f'HS ELETRÔNICOS  /  MANUAL DA MARCA                                     {i+1:02}',355,37,550,9,GRAY)
 c.showPage()
# visual plates
for mode in ['Identidade em uso','Paleta e hierarquia','Aplicações digitais']:
 c.setFillColor(HexColor(WHITE));c.rect(0,0,W,H,fill=1,stroke=0);para(mode,45,555,870,30,INK,True)
 if mode=='Identidade em uso':
  for x,y,bg,fg in [(45,295,INK,WHITE),(495,295,GREEN,INK),(45,75,'#FFFFFF',INK),(495,75,GRAY,WHITE)]:
   c.setFillColor(HexColor(bg));c.roundRect(x,y,420,180,16,fill=1,stroke=0);markpdf(c,x+20,y+45,95,fg);para('HS ELETRÔNICOS',x+128,y+111,275,24,fg,True);para('Cuidado técnico. Conversa clara.',x+128,y+75,265,12,fg)
 elif mode=='Paleta e hierarquia':
  for j,col in enumerate([INK,GREEN,WHITE,GRAY]):
   x=45+j*225;c.setFillColor(HexColor(col));c.setStrokeColor(HexColor(GRAY));c.roundRect(x,315,195,155,12,fill=1,stroke=1);para(col,x+16,350,170,17,INK if j in [1,2] else WHITE,True)
  para('Seu celular merece\natenção técnica.'.replace('\n',' '),45,265,550,40,INK,True);para('Reparação de celulares com foco em iPhones.',45,140,600,19,GRAY)
 else:
  c.setFillColor(HexColor(INK));c.roundRect(45,85,540,390,18,fill=1,stroke=0);markpdf(c,65,380,65,GREEN);para('HS ELETRÔNICOS',150,425,380,20,WHITE,True);para('Seu celular merece atenção técnica.',75,345,440,36,WHITE,True);para('Fale com a HS e entenda o próximo passo.',75,215,420,16,WHITE);c.setFillColor(HexColor(GREEN));c.roundRect(75,125,235,50,12,fill=1,stroke=0);para('Solicitar avaliação',91,160,220,18,INK,True)
  c.setFillColor(HexColor(GREEN));c.roundRect(620,85,295,390,18,fill=1,stroke=0);markpdf(c,642,361,80,INK);para('Como funciona a avaliação?',645,330,242,32,INK,True);para('Entenda cada etapa com a HS.',645,160,240,17,INK)
 para('APLICAÇÃO CONCEITUAL • PROPOSTA PARA VALIDAÇÃO',45,38,850,10,GRAY);c.showPage()
c.save()
(R/'01_Brandbook/Conteudo_editavel.md').write_text('# HS Eletrônicos • Brandbook v1.0\n\n'+ '\n\n'.join('## '+p['k']+' • '+p['t']+'\n\n'+p['lead']+'\n\n'+'\n\n'.join('### '+t+'\n'+b for t,b in p['items']) for p in P),encoding='utf-8')
(R/'02_Identidade/tokens.css').write_text(':root {\n  --hs-petroleo: #102A35;\n  --hs-lima: #B8EF48;\n  --hs-nevoa: #F5F7F2;\n  --hs-ardosia: #52666D;\n  --hs-font: Arial, Helvetica, sans-serif;\n  --hs-radius: 16px;\n  --hs-space: 8px;\n}\n',encoding='utf-8')
(R/'03_Site/Briefing.md').write_text('# Site • próxima etapa\n\nHospedagem prevista: Vercel, conforme solicitação. Site ainda não implementado.\n\n'+ '\n\n'.join(p['t']+'\n'+'\n'.join(t+': '+b for t,b in p['items']) for p in P[14:16])+'\n\nPendências: WhatsApp, domínio, endereço, horários, fotos reais, serviços, políticas e estoque. Definir responsável pela atualização.',encoding='utf-8')
(R/'04_Redes_Sociais/Direcao_e_roteiros.md').write_text('# Redes sociais • base de produção\n\n'+ '\n\n'.join('## '+p['t']+'\n'+'\n\n'.join('### '+t+'\n'+b for t,b in p['items']) for p in P[16:20]),encoding='utf-8')
(R/'LEIA-ME.md').write_text('# HS Eletrônicos\n\nProposta inicial de marca, criada a partir do briefing informado em 02/10/2026. Não contém fatos inventados sobre o cliente.\n\n- 01_Brandbook: manual PDF e conteúdo editável.\n- 02_Identidade: logos vetoriais SVG com letras em curvas e tokens CSS.\n- 03_Site: briefing para a futura implementação na Vercel.\n- 04_Redes_Sociais: direção editorial e roteiros iniciais.\n- 05_Fontes_e_QA: gerador e prévias para revisão.\n\nBelo Horizonte e região confirmados pelo cliente. Identidade criada do zero. Validar nome, visual, diferenciais, serviços e condições antes de publicar. As aplicações são conceituais. Nenhum site foi publicado e nenhum conteúdo foi enviado às redes.\n',encoding='utf-8')
doc=pdfium.PdfDocument(str(R/'01_Brandbook/HS_Eletronicos_Brandbook_v1.pdf'))
thumbs=[]
for i in range(len(doc)):
 im=doc[i].render(scale=0.65).to_pil().convert('RGB'); im.save(R/'05_Fontes_e_QA'/f'pagina-{i+1:02}.png');im.thumbnail((384,240));thumbs.append(im)
contact=Image.new('RGB',(384*5,265*5),'#D7DDDA');d=ImageDraw.Draw(contact)
for i,im in enumerate(thumbs):
 x=(i%5)*384;y=(i//5)*265;contact.paste(im,(x,y));d.text((x+10,y+242),str(i+1),fill='black')
contact.save(R/'05_Fontes_e_QA/contato.png')
print(f'Created {len(doc)} pages and SVG identity files in {R}')

