from pathlib import Path
R=Path(r'C:\Users\Fabio\Desktop\HS Eletronicos\03_Site\pwa')
files={
'components/ContactForm.tsx':'''"use client";
import { useEffect, useState } from 'react';
import { MessageCircle, Copy, ShieldCheck } from 'lucide-react';
import business from '@/lib/business.json';
import { composeMessage, whatsappUrl } from '@/lib/contact.mjs';
export function ContactForm(){
 const [category,setCategory]=useState('iPhone');const [model,setModel]=useState('');const [symptom,setSymptom]=useState('');const [status,setStatus]=useState('');const [online,setOnline]=useState(true);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);const value=new URLSearchParams(window.location.search).get('servico');if(value && ['iPhone','Celular','Outro eletrônico'].includes(value))setCategory(value);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 const message=composeMessage({category,model,symptom});const url=whatsappUrl(business.whatsapp,message);
 async function copy(){try{await navigator.clipboard.writeText(message);setStatus('Mensagem copiada. Você pode colar no WhatsApp.');}catch{setStatus('Não foi possível copiar automaticamente. Abra a prévia e copie o texto.');}}
 return <div className="contact-form"><h2>Conte o que aconteceu.</h2><p className="muted">Prepare sua mensagem. Você revisa e confirma o envio no WhatsApp.</p><fieldset><legend>Qual é o seu equipamento?</legend><div className="category-options">{['iPhone','Celular','Outro eletrônico'].map(item=><label key={item}><input type="radio" name="category" value={item} checked={category===item} onChange={()=>setCategory(item)}/><span>{item}</span></label>)}</div></fieldset><div className="field"><label className="field-label" htmlFor="model">Marca e modelo <span>opcional</span></label><input id="model" type="text" autoComplete="off" maxLength={80} placeholder="Ex.: iPhone 13" value={model} onChange={e=>setModel(e.target.value)}/></div><div className="field"><label className="field-label" htmlFor="symptom">O que você percebeu? <span>opcional</span></label><textarea id="symptom" maxLength={500} placeholder="Conte o sintoma e quando ele começou." value={symptom} onChange={e=>setSymptom(e.target.value)} aria-describedby="privacy-note"/><p id="privacy-note" className="field-note">Não inclua senhas, códigos de verificação ou informações pessoais do aparelho.</p></div><details className="message-preview"><summary>Revisar minha mensagem</summary><pre>{message}</pre></details>{!online&&<p className="notice">Você está offline. Pode preparar e copiar a mensagem, mas precisa de internet para abrir o WhatsApp.</p>}<div className="form-actions">{url&&online?<a className="button" href={url} target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/>Continuar no WhatsApp</a>:<button className="button" disabled><MessageCircle size={19}/>{online?'Canal em atualização':'Aguardando conexão'}</button>}<button className="button outline" type="button" onClick={copy}><Copy size={17}/>Copiar mensagem</button></div><p role="status" className="form-status">{status}</p><p className="field-note"><ShieldCheck size={14} style={{verticalAlign:'middle'}}/> Nada é enviado à HS por esta página. O texto fica apenas nesta sessão até você abrir o WhatsApp.</p></div>;
}
''',
'app/servicos/page.tsx':'''import { Breadcrumb, Eyebrow, ServiceCards, Process, ContactBanner } from '@/components/ui';
export const metadata={title:'Serviços de assistência técnica',description:'Assistência técnica para iPhones, celulares e consulta para outros eletrônicos em Belo Horizonte e região.'};
export default function Services(){return <><div className="container"><Breadcrumb label="Serviços"/><div className="page-intro"><Eyebrow>ASSISTÊNCIA TÉCNICA</Eyebrow><h1>O cuidado começa<br/>entendendo o problema.</h1><p>Escolha seu equipamento e conheça o próximo passo. Atendimento presencial e reparação 24 horas em Belo Horizonte e região.</p></div><div className="page-content"><ServiceCards/></div></div><Process/><ContactBanner/></>;}
''',
'app/servicos/[slug]/page.tsx':'''import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Check, Clock3, MessageCircle } from 'lucide-react';
import { services } from '@/lib/data';
import { Breadcrumb, Eyebrow, Faq, ContactBanner } from '@/components/ui';
export const dynamicParams=false;
export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.slug===slug);return {title:s?`Assistência para ${s.title}`:'Serviço não encontrado',description:s?.description};}
export default async function Service({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();const category=s.slug==='iphone'?'iPhone':s.slug==='celulares'?'Celular':'Outro eletrônico';return <><div className="container"><Breadcrumb label={`Serviços / ${s.title}`}/><div className="page-intro"><Eyebrow>{s.label}</Eyebrow><h1>Assistência para<br/>{s.title.toLowerCase()==='iphone'?'iPhone':s.title.toLowerCase()}.</h1><p>{s.intro}</p></div><div className="page-content detail-grid"><div><h2>Para começar a conversa</h2><ul className="check-list">{s.topics.map(t=><li key={t}><Check size={19}/>{t}</li>)}</ul><p>Informe o que você percebeu no aparelho. Esses detalhes ajudam Hugo a orientar como iniciar o atendimento.</p><div>{s.examples.map(e=><span className="tag" key={e}>{e}</span>)}</div><p className="notice">{s.note}</p><Link className="text-link" href="/servicos/">Ver todos os serviços</Link></div><aside className="detail-aside"><Clock3 size={28} color="#167c54"/><h2 style={{marginTop:22}}>Conte com a HS<br/>a qualquer hora.</h2><p>Atendimento presencial e reparação 24h em BH e região. Entre em contato para combinar o local e a avaliação.</p><Link className="button" href={`/contato/?servico=${encodeURIComponent(category)}`}><MessageCircle size={18}/>Combinar atendimento</Link><p className="field-note" style={{marginBottom:0}}>O prazo e as condições do serviço são confirmados conforme o caso.</p></aside></div></div><Faq/><ContactBanner/></>;}
''',
'app/contato/page.tsx':'''import { Clock3, MapPin, MessageCircle } from 'lucide-react';
import { Breadcrumb, Eyebrow } from '@/components/ui';
import { ContactForm } from '@/components/ContactForm';
import business from '@/lib/business.json';
export const metadata={title:'Fale com Hugo',description:'Combine seu atendimento presencial e reparação 24h com Hugo. WhatsApp (31) 99113-7969. Belo Horizonte e região.'};
export default function Contact(){return <div className="container"><Breadcrumb label="Atendimento"/><div className="page-intro"><Eyebrow>VAMOS CONVERSAR</Eyebrow><h1>Seu próximo passo<br/>começa aqui.</h1><p>Fale diretamente com Hugo para combinar o atendimento. Sem cadastro, com uma conversa clara.</p></div><div className="page-content contact-layout"><ContactForm/><aside className="dark-panel contact-aside"><span className="availability"><Clock3 size={14}/>ATENDIMENTO 24 HORAS</span><h2>Hugo<br/><span style={{color:'#bfc3c7'}}>HS Eletrônicos</span></h2><p>Conte o que aconteceu com o seu aparelho. Vamos orientar como começar a avaliação.</p><a className="contact-phone" href={`tel:+${business.whatsapp}`}>{business.phoneDisplay}</a><div className="contact-meta"><p><MapPin size={19}/>Belo Horizonte e região</p><p><Clock3 size={19}/>Atendimento presencial e reparação 24h</p><p><MessageCircle size={19}/>Combine o local diretamente com Hugo</p></div><p className="field-note">O prazo para concluir o reparo depende da avaliação, das condições do aparelho e da disponibilidade de peças.</p></aside></div></div>;}
''',
'app/sobre/page.tsx':'''import { Breadcrumb, Eyebrow, ContactBanner } from '@/components/ui';
import { Brand } from '@/components/Brand';
export const metadata={title:'Sobre a HS',description:'Conheça a HS Eletrônicos e Hugo, responsável pela assistência técnica de celulares em Belo Horizonte e região.'};
export default function About(){return <><div className="container"><Breadcrumb label="Sobre a HS"/><div className="page-intro"><Eyebrow>QUEM ESTÁ DO OUTRO LADO</Eyebrow><h1>Técnica no cuidado.<br/>Clareza na conversa.</h1><p>A HS Eletrônicos cuida de aparelhos que fazem parte da sua rotina, com foco em reparação de celulares e iPhones.</p></div><div className="page-content two-column"><div><h2>Prazer, Hugo.</h2><p>Hugo é o responsável pela HS Eletrônicos. Em Belo Horizonte e região, oferece atendimento presencial e reparação 24 horas.</p><p>O primeiro passo é uma conversa: entender o modelo do aparelho, ouvir o que aconteceu e combinar o atendimento para a avaliação.</p><p>A compra e venda de equipamentos novos e seminovos também faz parte do negócio. Para conhecer as condições e a disponibilidade, fale diretamente com Hugo.</p><div className="notice">A HS atua na reparação de eletrônicos. O atendimento de cada categoria e serviço é confirmado conforme o equipamento.</div></div><div className="brand-card"><Brand/><h2>Cuidado técnico.<br/>Conversa clara.</h2><p>O símbolo da placa eletrônica representa a atenção aos detalhes por trás de cada equipamento.</p><p style={{marginBottom:0}}>Belo Horizonte e região<br/>Atendimento presencial e reparação 24h</p></div></div></div><ContactBanner/></>;}
''',
'app/instalar/page.tsx':'''import { Download, WifiOff, Smartphone, ShieldCheck } from 'lucide-react';
import { Breadcrumb, Eyebrow } from '@/components/ui';
import { InstallControl } from '@/components/pwa';
export const metadata={title:'Instalar o aplicativo',description:'Tenha os serviços e o contato da HS Eletrônicos na tela inicial do seu celular. Sem cadastro.'};
export default function Install(){return <div className="container"><Breadcrumb label="Aplicativo"/><div className="page-intro"><Eyebrow>A HS, MAIS PERTO</Eyebrow><h1>Na sua tela inicial.<br/>Quando você precisar.</h1><p>Instale a HS Eletrônicos no celular ou computador para acessar os serviços e preparar seu atendimento com facilidade.</p></div><div className="page-content two-column"><div className="info-card"><div className="install-art"><img src="/icons/icon-192.png" alt="Ícone do aplicativo HS Eletrônicos" width="96" height="96"/><div><h2>HS Eletrônicos</h2><p>Assistência técnica • BH e região</p></div></div><InstallControl/></div><aside className="dark-panel"><h2>Feito para facilitar.</h2><div className="install-benefits">{[{icon:Smartphone,title:'Acesso direto',text:'Abra pela tela inicial, sem precisar procurar o site de novo.'},{icon:WifiOff,title:'Informações offline',text:'Depois do primeiro acesso completo, consulte as páginas salvas mesmo sem internet. O WhatsApp precisa de conexão.'},{icon:ShieldCheck,title:'Sem cadastro',text:'Sem conta, senha ou notificações. Você decide quando falar com a HS.'}].map(b=><div key={b.title}><b.icon size={23}/><div><h3>{b.title}</h3><p>{b.text}</p></div></div>)}</div></aside></div></div>;}
''',
'app/privacidade/page.tsx':'''import Link from 'next/link';
import { Breadcrumb, Eyebrow } from '@/components/ui';
export const metadata={title:'Privacidade',description:'Como funciona o uso de informações no aplicativo da HS Eletrônicos.'};
export default function Privacy(){return <div className="container legal"><Breadcrumb label="Privacidade"/><div className="page-intro"><Eyebrow>INFORMAÇÃO E CONTROLE</Eyebrow><h1>Sua privacidade.</h1><p>Este aviso descreve o funcionamento desta versão do site e aplicativo da HS Eletrônicos.</p></div><article className="page-content"><h2>O que acontece nesta página</h2><p>O site não exige cadastro, não utiliza formulários com envio para um servidor próprio e não contém ferramentas de publicidade ou analytics. As informações digitadas para preparar uma mensagem permanecem na memória da página; não são gravadas pelo aplicativo como histórico.</p><h2>Contato pelo WhatsApp</h2><p>Ao selecionar Continuar no WhatsApp, o texto preparado é incluído no link que abre o serviço externo. O WhatsApp pode processar esse acesso conforme sua própria política. Você decide se confirma o envio à HS. Não inclua senhas, códigos de verificação, documentos ou conteúdo privado do aparelho.</p><h2>Funcionamento offline</h2><p>O aplicativo armazena cópias das páginas e arquivos públicos no navegador para funcionar offline. Isso não armazena o texto digitado no atendimento. Para remover essas cópias, limpe os dados deste site nas configurações do navegador; desinstalar o atalho pode não apagar todos os dados.</p><h2>Hospedagem e registros técnicos</h2><p>O provedor de hospedagem pode processar informações técnicas, como IP e registros de acesso, para entregar e proteger o site. Não são adicionados cookies de publicidade ou rastreadores nesta versão. Mudanças de ferramentas devem ser refletidas neste aviso.</p><h2>Atendimento e seus direitos</h2><p>Para tratar de informações compartilhadas com a HS durante o atendimento, fale com Hugo pelo canal comercial. A retenção e o tratamento dos registros de atendimento dependem da operação e das obrigações aplicáveis; não são gerenciados por este aplicativo.</p><Link className="text-link" href="/contato/">Falar com Hugo sobre privacidade</Link></article></div>;}
''',
'app/links/page.tsx':'''import Link from 'next/link';
import { MessageCircle, Cpu, Download } from 'lucide-react';
import { Breadcrumb, Eyebrow } from '@/components/ui';
export const metadata={title:'Acesse a HS',description:'Serviços, atendimento e aplicativo da HS Eletrônicos.'};
export default function Links(){return <div className="container"><Breadcrumb label="Acesso rápido"/><div className="page-intro"><Eyebrow>HS ELETRÔNICOS</Eyebrow><h1>Como podemos ajudar?</h1><p>Belo Horizonte e região. Atendimento presencial e reparação 24 horas.</p></div><div className="page-content links-stack"><Link href="/contato/"><MessageCircle/>Combinar atendimento com Hugo</Link><Link href="/servicos/"><Cpu/>Conhecer os serviços</Link><Link href="/instalar/"><Download/>Instalar o aplicativo</Link></div></div>;}
''',
'app/offline/page.tsx':'''import Link from 'next/link';
export const metadata={title:'Você está offline'};
export default function Offline(){return <section className="container not-found"><p className="eyebrow">SEM CONEXÃO</p><h1>Seguimos por aqui.</h1><p>Você pode consultar as informações salvas.<br/>Para falar com Hugo, conecte-se à internet.</p><Link className="button" href="/">Voltar ao início</Link></section>;}
''',
'app/not-found.tsx':'''import Link from 'next/link';
export default function NotFound(){return <section className="container not-found"><p className="eyebrow">PÁGINA NÃO ENCONTRADA</p><h1>Vamos por<br/>outro caminho.</h1><p>Este endereço não está disponível.<br/>Encontre nossos serviços ou combine seu atendimento.</p><div className="hero-actions" style={{justifyContent:'center'}}><Link className="button" href="/">Voltar ao início</Link><Link className="button outline" href="/contato/">Falar com Hugo</Link></div></section>;}
''',
'vercel.json':'''{"framework":"nextjs","buildCommand":"npm run build","outputDirectory":"out","headers":[{"source":"/sw.js","headers":[{"key":"Cache-Control","value":"no-cache, no-store, must-revalidate"},{"key":"Service-Worker-Allowed","value":"/"}]},{"source":"/manifest.webmanifest","headers":[{"key":"Content-Type","value":"application/manifest+json"},{"key":"Cache-Control","value":"no-cache"}]},{"source":"/(.*)","headers":[{"key":"X-Content-Type-Options","value":"nosniff"},{"key":"Referrer-Policy","value":"strict-origin-when-cross-origin"},{"key":"X-Frame-Options","value":"DENY"},{"key":"Permissions-Policy","value":"camera=(), microphone=(), geolocation=()"}]}]}
''',
'public/robots.txt':'''User-agent: *\nDisallow: /\n''',
'tsconfig.json':'''{"compilerOptions":{"target":"ES2017","lib":["dom","dom.iterable","esnext"],"allowJs":true,"skipLibCheck":true,"strict":true,"noEmit":true,"esModuleInterop":true,"module":"esnext","moduleResolution":"bundler","resolveJsonModule":true,"isolatedModules":true,"jsx":"react-jsx","incremental":true,"plugins":[{"name":"next"}],"paths":{"@/*":["./*"]}},"include":["next-env.d.ts","**/*.ts","**/*.tsx",".next/types/**/*.ts",".next/dev/types/**/*.ts"],"exclude":["node_modules"]}
'''
}
for path,content in files.items():
 p=R/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content,encoding='utf-8')
print('Páginas internas e atendimento implementados.')
