export const services = [
 { slug: 'iphone', title: 'iPhone', label: 'FOCO NO SEU IPHONE', description: 'Seu iPhone merece atenção em cada detalhe. Conte o que aconteceu para orientar a avaliação.', icon: 'phone', topics: ['Informe o modelo', 'Descreva o sintoma', 'Combine o atendimento'], intro: 'Quando algo muda no funcionamento do seu iPhone, o primeiro passo é entender o que aconteceu. Hugo orienta como começar a avaliação.', examples: ['Mudanças no funcionamento', 'Dificuldade para carregar', 'Problemas percebidos na tela'], note: 'Os sintomas ajudam a iniciar a conversa. A causa e as possibilidades de reparação dependem de avaliação.' },
 { slug: 'celulares', title: 'Celulares', label: 'CUIDADO COM A SUA ROTINA', description: 'Assistência para o aparelho que acompanha você. Consulte o atendimento para sua marca e modelo.', icon: 'phone', topics: ['Consulte marca e modelo', 'Explique o que mudou', 'Entenda o próximo passo'], intro: 'Seu celular faz parte da sua rotina. Se ele apresentou uma falha, informe a marca, o modelo e quando o problema começou para combinar a avaliação.', examples: ['Falhas de funcionamento', 'Problemas de energia', 'Danos percebidos no aparelho'], note: 'A disponibilidade do serviço e de peças é confirmada conforme o equipamento e a avaliação.' },
 { slug: 'eletronicos', title: 'Outros eletrônicos', label: 'CADA EQUIPAMENTO, UMA AVALIAÇÃO', description: 'Tem outro equipamento precisando de atenção? Consulte Hugo sobre a possibilidade de atendimento.', icon: 'circuit', topics: ['Identifique o equipamento', 'Informe marca e modelo', 'Confirme se é atendido'], intro: 'A HS também trabalha com eletrônicos. Entre em contato com os dados do seu equipamento para confirmar se a categoria e o serviço são atendidos.', examples: ['Tipo de equipamento', 'Marca e modelo', 'Sintoma e histórico percebido'], note: 'O atendimento de outras categorias é confirmado caso a caso. Não há promessa de reparo para todo tipo de equipamento.' }
] as const;
export const faqs = [
 ['Como funciona o atendimento 24 horas?', 'A HS oferece atendimento presencial e reparação 24 horas. Entre em contato com Hugo para combinar o local e orientar a avaliação. O tempo para concluir o reparo depende do aparelho, da avaliação e das condições do serviço.'],
 ['Onde a HS atende?', 'Em Belo Horizonte e região. Combine o atendimento diretamente com Hugo pelo WhatsApp. O local e a possibilidade de atendimento na sua região são confirmados na conversa.'],
 ['Vocês atendem iPhones?', 'Sim. A HS tem foco em reparação de celulares, especialmente iPhones. Informe o modelo e o que aconteceu para entender o próximo passo.'],
 ['Posso saber o valor antes da avaliação?', 'Conte o sintoma e informe o modelo para iniciar a conversa. O valor, as condições de avaliação e o prazo precisam ser confirmados com Hugo conforme o caso.'],
 ['O que devo informar no primeiro contato?', 'Marca, modelo, sintoma e quando o problema começou. Não envie senhas, códigos de verificação ou dados pessoais armazenados no aparelho.'],
 ['A HS também compra e vende aparelhos?', 'Sim, a compra e venda de equipamentos novos e seminovos também faz parte do negócio. Consulte Hugo para saber as condições e a disponibilidade. Este site é dedicado aos serviços de assistência.']
] as const;
